<?php

namespace ContainerZ5gxQhP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MmExF1tService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mmExF1t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mmExF1t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator.mmExF1t.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.mmExF1t": it references class "App\\Entity\\Article" but no such service exists.'],
            'request' => ['privates', '.errored.w48F1sv', NULL, 'Cannot determine controller argument for "App\\Controller\\ViewController::view()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'article' => 'App\\Entity\\Article',
            'request' => '?',
        ]);
    }
}
