<?php

namespace ContainerMWttPYx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LUSv6PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LUSv6_p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LUSv6_p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator.LUSv6_p.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.LUSv6_p": it references class "App\\Entity\\Article" but no such service exists.'],
            'entityManager' => ['privates', '.errored.efDHffG', NULL, 'Cannot determine controller argument for "App\\Controller\\EditController::edit()": the $entityManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
        ], [
            'article' => 'App\\Entity\\Article',
            'entityManager' => '?',
        ]);
    }
}
